# Generated by Django 2.0.7 on 2018-07-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=30)),
                ('goods_number', models.IntegerField()),
                ('goods_price', models.FloatField()),
            ],
        ),
    ]
