# Generated by Django 2.0.7 on 2018-07-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品管理'},
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(max_length=30, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_number',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.FloatField(verbose_name='价格'),
        ),
    ]
